# Generated by Django 6.0.2 on 2026-02-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('hazard_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('msds_link', models.URLField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('EQUIPMENT', 'Equipment')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_intake', models.IntegerField()),
                ('scaling_factor', models.FloatField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lab')),
            ],
        ),
    ]
