# Generated by Django 6.0.2 on 2026-02-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='chemical',
            name='max_threshold',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_threshold',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
